[template]
ignore = ["target", "mygraphics/src/bin"]
exclude = ["target", "mygraphics/src/bin"]

[placeholders]
integration = { prompt = "What integration type?", choices = ["cargo-gpu", "spirv-builder"], default = "cargo-gpu", type = "string" }

[conditional.'integration != "spirv-builder"']
ignore = [ "rust-toolchain.toml" ]
