[package]
name = "ash-graphics"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["use-compiled-tools"]
use-installed-tools = ["spirv-builder/use-installed-tools"]
use-compiled-tools = ["spirv-builder/use-compiled-tools"]
[dependencies]
ash-graphics-shaders = { path = "../ash-graphics-shaders" }

ash.workspace = true
ash-window.workspace = true
raw-window-handle.workspace = true
winit.workspace = true
anyhow.workspace = true
bytemuck.workspace = true

[build-dependencies]
spirv-builder.workspace = true
anyhow.workspace = true
