[template]
ignore = ["target"]
exclude = ["target"]

[placeholders]
integration_type = { prompt = "What integration type?", choices = ["cargo-gpu", "spirv-builder"], default = "cargo-gpu", type = "string" }

[conditional.'integration_type != "spirv-builder"']
ignore = [ "rust-toolchain.toml" ]